// What the simulated collaborator writes: a hundred lines by women poets,
// each with its poet, all old enough to be in the public domain.

let phrases = [
  ("Hope is the thing with feathers that perches in the soul", "Emily Dickinson"),
  ("Because I could not stop for Death, he kindly stopped for me", "Emily Dickinson"),
  ("I'm Nobody! Who are you? Are you Nobody too?", "Emily Dickinson"),
  ("Tell all the truth but tell it slant", "Emily Dickinson"),
  ("I dwell in Possibility, a fairer house than Prose", "Emily Dickinson"),
  ("The brain is wider than the sky", "Emily Dickinson"),
  ("After great pain, a formal feeling comes", "Emily Dickinson"),
  ("There's a certain slant of light, winter afternoons", "Emily Dickinson"),
  ("My life closed twice before its close", "Emily Dickinson"),
  ("I heard a fly buzz when I died", "Emily Dickinson"),
  ("Success is counted sweetest by those who ne'er succeed", "Emily Dickinson"),
  (
    "A word is dead when it is said, some say; I say it just begins to live that day",
    "Emily Dickinson",
  ),
  ("Forever is composed of nows", "Emily Dickinson"),
  ("The soul selects her own society, then shuts the door", "Emily Dickinson"),
  ("Much madness is divinest sense to a discerning eye", "Emily Dickinson"),
  ("To make a prairie it takes a clover and one bee", "Emily Dickinson"),
  ("I taste a liquor never brewed, from tankards scooped in pearl", "Emily Dickinson"),
  (
    "Wild nights! Wild nights! Were I with thee, wild nights should be our luxury",
    "Emily Dickinson",
  ),
  ("This is my letter to the world that never wrote to me", "Emily Dickinson"),
  ("There is no frigate like a book to take us lands away", "Emily Dickinson"),
  ("Remember me when I am gone away, gone far away into the silent land", "Christina Rossetti"),
  ("Who has seen the wind? Neither I nor you", "Christina Rossetti"),
  ("Does the road wind up-hill all the way? Yes, to the very end", "Christina Rossetti"),
  ("My heart is like a singing bird whose nest is in a watered shoot", "Christina Rossetti"),
  ("In the bleak midwinter, frosty wind made moan", "Christina Rossetti"),
  ("Morning and evening maids heard the goblins cry", "Christina Rossetti"),
  ("When I am dead, my dearest, sing no sad songs for me", "Christina Rossetti"),
  (
    "Better by far you should forget and smile than that you should remember and be sad",
    "Christina Rossetti",
  ),
  ("How do I love thee? Let me count the ways", "Elizabeth Barrett Browning"),
  (
    "I love thee to the depth and breadth and height my soul can reach",
    "Elizabeth Barrett Browning",
  ),
  (
    "If thou must love me, let it be for nought except for love's sake only",
    "Elizabeth Barrett Browning",
  ),
  (
    "Earth's crammed with heaven, and every common bush afire with God",
    "Elizabeth Barrett Browning",
  ),
  ("Do ye hear the children weeping, O my brothers", "Elizabeth Barrett Browning"),
  ("No coward soul is mine, no trembler in the world's storm-troubled sphere", "Emily Brontë"),
  ("Cold in the earth, and the deep snow piled above thee", "Emily Brontë"),
  ("I'll walk where my own nature would be leading", "Emily Brontë"),
  ("Riches I hold in light esteem, and love I laugh to scorn", "Emily Brontë"),
  (
    "My soul is awakened, my spirit is soaring, and carried aloft on the wings of the breeze",
    "Anne Brontë",
  ),
  ("There will come soft rains and the smell of the ground", "Sara Teasdale"),
  ("I am not yours, not lost in you, not lost, although I long to be", "Sara Teasdale"),
  ("Life has loveliness to sell, all beautiful and splendid things", "Sara Teasdale"),
  ("Spend all you have for loveliness, buy it and never count the cost", "Sara Teasdale"),
  ("When I am dead and over me bright April shakes out her rain-drenched hair", "Sara Teasdale"),
  ("I asked the heaven of stars what I should give my love", "Sara Teasdale"),
  ("My candle burns at both ends; it will not last the night", "Edna St. Vincent Millay"),
  (
    "I will be the gladdest thing under the sun! I will touch a hundred flowers and not pick one",
    "Edna St. Vincent Millay",
  ),
  (
    "All I could see from where I stood was three long mountains and a wood",
    "Edna St. Vincent Millay",
  ),
  ("Euclid alone has looked on Beauty bare", "Edna St. Vincent Millay"),
  (
    "The world stands out on either side no wider than the heart is wide",
    "Edna St. Vincent Millay",
  ),
  (
    "Safe upon the solid rock the ugly houses stand: come and see my shining palace built upon the sand",
    "Edna St. Vincent Millay",
  ),
  (
    "What lips my lips have kissed, and where, and why, I have forgotten",
    "Edna St. Vincent Millay",
  ),
  ("I walk down the garden paths, and all the daffodils are blowing", "Amy Lowell"),
  ("Christ! What are patterns for?", "Amy Lowell"),
  ("When I go away from you the world beats dead like a slackened drum", "Amy Lowell"),
  ("Whirl up, sea, whirl your pointed pines", "H.D."),
  ("Rose, harsh rose, marred and with stint of petals", "H.D."),
  (
    "I, too, dislike it: there are things that are important beyond all this fiddle",
    "Marianne Moore",
  ),
  ("Imaginary gardens with real toads in them", "Marianne Moore"),
  ("Rose is a rose is a rose is a rose", "Gertrude Stein"),
  ("Give me your tired, your poor, your huddled masses yearning to breathe free", "Emma Lazarus"),
  ("I lift my lamp beside the golden door", "Emma Lazarus"),
  ("'Twas mercy brought me from my pagan land", "Phillis Wheatley"),
  ("Imagination! who can sing thy force?", "Phillis Wheatley"),
  ("If ever two were one, then surely we", "Anne Bradstreet"),
  ("I prize thy love more than whole mines of gold", "Anne Bradstreet"),
  ("Thou ill-formed offspring of my feeble brain", "Anne Bradstreet"),
  ("The moon has set, and the Pleiades; it is midnight, and I sleep alone", "Sappho"),
  ("Sweet mother, I cannot weave; slender Aphrodite has overcome me with longing", "Sappho"),
  (
    "Some say an army of horsemen, some of ships, is the fairest thing on the black earth, but I say it is what one loves",
    "Sappho",
  ),
  ("Laugh, and the world laughs with you; weep, and you weep alone", "Ella Wheeler Wilcox"),
  ("Avoid the reeking herd, shun the polluted flock", "Elinor Wylie"),
  ("I was, being human, born alone; I am, being woman, hard beset", "Elinor Wylie"),
  (
    "Three summers since I chose a maid, too young maybe, but more's to do at harvest-time than bide and woo",
    "Charlotte Mew",
  ),
  (
    "I must not think of thee; and, tired yet strong, I shun the thought that lurks in all delight",
    "Alice Meynell",
  ),
  (
    "Listen, with faint dry sound, like steps of passing ghosts, the leaves, frost-crisp'd, break from the trees and fall",
    "Adelaide Crapsey",
  ),
  (
    "O why do you walk through the fields in gloves, missing so much and so much?",
    "Frances Cornford",
  ),
  ("For thou art all that I can prize, my joy, my life, my rest", "Katherine Philips"),
  ("Love in fantastic triumph sat, whilst bleeding hearts around him flowed", "Aphra Behn"),
  (
    "Give me, O indulgent Fate! give me yet before I die a sweet, but absolute retreat",
    "Anne Finch",
  ),
  ("In such a night, when every louder wind is to its distant cavern safe confined", "Anne Finch"),
  ("The boy stood on the burning deck whence all but he had fled", "Felicia Hemans"),
  ("The stately homes of England, how beautiful they stand!", "Felicia Hemans"),
  (
    "Ah! hills beloved! where once, a happy child, your beechen shades, your turf, your flowers among",
    "Charlotte Smith",
  ),
  ("Pavement slippery, people sneezing, lords in ermine, beggars freezing", "Mary Robinson"),
  ("Life! I know not what thou art, but know that thou and I must part", "Anna Laetitia Barbauld"),
  (
    "O suns and skies and clouds of June, and flowers of June together, ye cannot rival for one hour October's bright blue weather",
    "Helen Hunt Jackson",
  ),
  ("Mine eyes have seen the glory of the coming of the Lord", "Julia Ward Howe"),
  ("Green is the plane-tree in the square, the other trees are brown", "Amy Levy"),
  ("Egypt's might is tumbled down, down a-down the deeps of thought", "Mary Elizabeth Coleridge"),
  (
    "I grieve and dare not show my discontent, I love and yet am forced to seem to hate",
    "Elizabeth I",
  ),
  (
    "When night's black mantle could most darkness prove, and sleep, death's image, did my senses hire",
    "Lady Mary Wroth",
  ),
  (
    "I have just seen a most beautiful thing, slim and still, against a gold, gold sky, a straight black cypress",
    "Angelina Weld Grimké",
  ),
  (
    "The heart of a woman goes forth with the dawn, as a lone bird, soft winging, so restlessly on",
    "Georgia Douglas Johnson",
  ),
  (
    "I sit and sew, a useless task it seems, my hands grown tired, my head weighed down with dreams",
    "Alice Dunbar-Nelson",
  ),
  (
    "Lightly, O lightly we bear her along, she sways like a flower in the wind of our song",
    "Sarojini Naidu",
  ),
  (
    "Like a huge python, winding round and round the rugged trunk, indented deep with scars",
    "Toru Dutt",
  ),
  (
    "West wind, blow from your prairie nest, blow from the mountains, blow from the west",
    "E. Pauline Johnson",
  ),
  (
    "When I consider Life and its few years, a wisp of fog betwixt us and the sun",
    "Lizette Woodworth Reese",
  ),
  ("Across the narrow beach we flit, one little sandpiper and I", "Celia Thaxter"),
  ("Evening and the flat land, rich and sombre and always silent", "Willa Cather"),
]
